input RegisterInput {
  email: String!
  password: String!
  name: String
}

input LoginInput {
  email: String!
  password: String!
}

input UpdateUserInput{
  name: String
}

input CreateDoctorInput {
  name: String!
  specialty: String!
  email: String!
  phone: String!
}

input CreatePatientInput {
  firstName: String!
  lastName: String!
  email: String
  phone: String!
}

input UpdatePatientInput {
  id: ID!
  firstName: String
  lastName: String
  email: String
  phone: String
}

input CreateAppointmentInput {
  doctorId: ID!
  patientId: ID!
  date: String!
  startTime: String!
  endTime: String!
}

input UpdateAppointmentInput {
  id: ID!
  date: String
  startTime: String
  endTime: String
  status: String
}
