type Query {
  me: User
  users(role: UserRole): [User!]!
  companies(search: String): [Company!]!
  company(id: ID!): Company
  personsByCompany(companyId: ID!, search: String): [Person!]!
  appointmentsByCompany(companyId: ID!, date: String): [Appointment!]!
  
  persons: [Person!]!
  appointments(date: String): [Appointment!]!
  appointment(id: ID!): Appointment
  tasks(filter: TaskFilterInput): [Task!]!
  task(id: ID!): Task
}

type Mutation {
  register(input: RegisterInput!): AuthPayload!
  login(input: LoginInput!): AuthPayload!
  updateUser(input: UpdateUserInput!): UpdatedUserResponse!
  
  createCompany(input: CreateCompanyInput!): Company!
  updateCompany(input: UpdateCompanyInput!): Company!
  
  createPerson(input: CreatePersonInput!): Person!
  updatePerson(input: UpdatePersonInput!): Person!
  
  createDeal(input: CreateDealInput!): Deal!
  
  createAppointment(input: CreateAppointmentInput!): Appointment!
  updateAppointmentStatus(input: UpdateAppointmentStatusInput!): Appointment!
  updateAppointment(input: UpdateAppointmentInput!): Appointment!
  deleteAppointment(id: ID!): Appointment!
  
  createTask(input: CreateTaskInput!): Task!
  updateTask(input: UpdateTaskInput!): Task!
  deleteTask(id: ID!): Task!

  registerPushToken(token: String!): Boolean
}
