# import * from './types.graphql'
# import * from './inputs.graphql'

type Query {
  me: User
  doctors: [Doctor!]!
  patients(search: String): [Patient!]!
  appointments: [Appointment!]!
  appointmentsByDate(date: String!): [Appointment!]!
}

type Mutation {
  register(input: RegisterInput!): AuthPayload!
  login(input: LoginInput!): AuthPayload!
  updateUser(input: UpdateUserInput!): UpdatedUserResponse!
  createDoctor(input: CreateDoctorInput!): Doctor!
  createPatient(input: CreatePatientInput!): Patient!
  createAppointment(input: CreateAppointmentInput!): Appointment!
}
