enum UserRole {
  ADMIN
  STAFF
  DOCTOR
}

enum DealStatus {
  OPEN
  WON
  LOST
}

enum AppointmentStatus {
  PENDING
  CONFIRMED
  CANCELED
  COMPLETED
}

type User {
  id: ID!
  email: String!
  name: String
  role: UserRole!
  createdAt: String!
  updatedAt: String!
  appointments: [Appointment!]
}

type Company {
  id: ID!
  name: String!
  email: String
  phone: String
  createdAt: String!
  updatedAt: String!
  persons: [Person!]
  deals: [Deal!]
  appointments: [Appointment!]
}

type Person {
  id: ID!
  firstName: String!
  lastName: String!
  email: String
  phone: String
  role: String
  notes: String
  companyId: String!
  company: Company!
  appointments: [Appointment!]
  createdAt: String!
  updatedAt: String!
}

type Deal {
  id: ID!
  title: String!
  amount: Float!
  status: DealStatus!
  companyId: String!
  company: Company!
  createdAt: String!
  updatedAt: String!
}

type Appointment {
  id: ID!
  companyId: String!
  company: Company!
  personId: String!
  person: Person!
  userId: String!
  user: User!
  date: String!
  startTime: String!
  endTime: String!
  status: AppointmentStatus!
  createdAt: String!
  updatedAt: String!
}

type AuthPayload {
  token: String!
  user: User!
}

type UpdatedUserResponse {
  user: User!
}
