type User {
  id: ID!
  email: String!
  name: String
  createdAt: String!
  updatedAt: String!
}

type AuthPayload {
  token: String!
  user: User!
}

type UpdatedUserResponse {
  user: User!
}

type Doctor {
  id: ID!
  name: String!
  specialty: String!
  email: String!
  phone: String!
  createdAt: String!
}

type Patient {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  phone: String!
  createdAt: String!
}

type Appointment {
  id: ID!
  doctor: Doctor!
  patient: Patient!
  date: String!
  startTime: String!
  endTime: String!
  status: AppointmentStatus!
  createdAt: String!
}

enum AppointmentStatus {
  PENDING
  CONFIRMED
  CANCELED
  COMPLETED
}
