enum ScreenNames {
  AuthScreen = "AuthScreen",
  RegisterScreen = "RegisterScreen",
  LoginWithQRScreen = "LoginWithQRScreen",
  GenerateQRScreen = "GenerateQRScreen",
  UsersListScreen = "UsersListScreen",
 HomeScreen = "HomeScreen",
  ArticleDetails = "ArticleDetails",
  SettingsScreen = "SettingsScreen",
  EditProfileScreen = "EditProfileScreen",
  BookAppointmentScreen = "BookAppointmentScreen",
  AppointmentsList = "AppointmentsList",
  AppointmentDetails = "AppointmentDetails",
  AddPatientScreen = "AddPatientScreen",
  PatientsList = "PatientsList",
  PatientDetails = "PatientDetails",
  EditPatient = "EditPatient",
  EditAppointment = "EditAppointment",
  CompaniesScreen = "CompaniesScreen",
  PersonsScreen = "PersonsScreen",
  CreatePersonScreen = "CreatePersonScreen",
  CreateCompanyScreen = "CreateCompanyScreen",
  CompanyDetailsScreen = "CompanyDetailsScreen",
  CompanyProfileScreen = "CompanyProfileScreen",
  EditCompanyScreen = "EditCompanyScreen",
  DealsScreen = "DealsScreen",
  CreateDealScreen = "CreateDealScreen",
  CompanyAppointmentsScreen = "CompanyAppointmentsScreen",
  PersonDetailsScreen = "PersonDetailsScreen",
  // EditPersonScreen
  EditPersonScreen = "EditPersonScreen",
  CreateTaskScreen = "CreateTaskScreen",
  TaskDetailsScreen = "TaskDetailsScreen",
  TasksScreen = "TasksScreen",
}

export default ScreenNames;
